name: 'Sync Clockify to Project'
description: 'Sync Clockify time entries to GitHub Projects'
author: 'floholz'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'clock'
  color: 'orange'

# Define your inputs here.
inputs:
  project-url:
    description: 'Url to the GitHub Project'
    required: true
  github-token:
    description: 'GitHub personal access token with write access to the project'
    required: true
  clockify-workspace-id:
    description: 'Clockify workspace id'
    required: true
  clockify-api-key:
    description: 'Clockify API Key'
    required: true

# Define your outputs here.
outputs:
  times:
    description: 'Time entries array'

runs:
  using: node20
  main: dist/index.js
